import { Project } from './types'

export const GITHUB_USER = 'pozhidaevnikita2743-arch'
export const GITHUB_BASE  = `https://github.com/${GITHUB_USER}`
const GHPAGES = `https://${GITHUB_USER}.github.io`

export const projects: Project[] = [
  {
    id: 'lumora',
    title: 'Lumora',
    description: 'Independent design & engineering studio landing — bold typography, dark aesthetic, smooth scroll animations, all in a single self-contained HTML file.',
    descriptionRu: 'Лендинг независимой дизайн-студии — жирная типографика, тёмная эстетика, плавные скролл-анимации. Один самодостаточный HTML-файл.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    githubBase: GITHUB_BASE,
    live: 'https://lumora-tan-iota.vercel.app',
    image: '/img/projects/lumora.jpg',
    year: 2026,
    category: 'portfolio',
  },
  {
    id: 'oaklet-store',
    title: 'OAKLET Store',
    description: 'Clothing e-commerce catalog with cart, VK/Telegram order flow, filterable catalog, and product detail pages.',
    descriptionRu: 'Интернет-магазин одежды: корзина, оформление заказа через VK/Telegram, фильтруемый каталог и страницы товаров.',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'CSS Modules'],
    github: 'oaklet-store-v2-',
    githubBase: GITHUB_BASE,
    live: 'https://oaklet.ru',
    image: '/img/projects/oaklet-store.jpg',
    previewPosition: '0% 35%',   // skip giant hero text, show catalog area
    featured: true,
    year: 2025,
    category: 'commercial',
  },
  {
    id: 'kaltansky-modern',
    title: 'Kaltansky Modern',
    description: 'Modern-style website for a coal mining company. Clean layout, professional imagery, fully responsive.',
    descriptionRu: 'Сайт в современном стиле для угледобывающей компании. Чистая вёрстка, профессиональные фото, полная адаптивность.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'kaltansky-modern',
    githubBase: GITHUB_BASE,
    live: `${GHPAGES}/kaltansky-modern/`,
    image: '/img/projects/kaltansky-modern.jpg',
    year: 2025,
    category: 'corporate',
  },
  {
    id: 'kaltansky-corporate',
    title: 'Kaltansky Corporate',
    description: 'Corporate-style website for the same coal mining company — distinct visual language from the modern version.',
    descriptionRu: 'Корпоративный сайт той же угольной компании — иной визуальный язык по сравнению с современной версией.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    github: 'kaltansky-corporate',
    githubBase: GITHUB_BASE,
    live: `${GHPAGES}/kaltansky-corporate/`,
    image: '/img/projects/kaltansky-corporate.jpg',
    year: 2025,
    category: 'corporate',
  },
  {
    id: 'elena-vrublevskaya',
    title: 'Elena Vrublevskaya',
    description: 'Personal website for a quantum coach and numerologist. Services, reviews, and Telegram contact flow.',
    descriptionRu: 'Персональный сайт квантового коуча и нумеролога. Услуги, отзывы и форма связи через Telegram.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    githubBase: GITHUB_BASE,
    live: 'https://elenavrublevskaya.ru',
    image: '/img/projects/elena-vrublevskaya.jpg',
    year: 2025,
    category: 'commercial',
  },
  {
    id: 'photo-site-multilang',
    title: 'Photo Site Multi-lang',
    description: 'Photographer portfolio in 3 languages — custom i18n implementation, no frameworks.',
    descriptionRu: 'Портфолио фотографа на 3 языках — своя реализация i18n без фреймворков.',
    tech: ['HTML', 'CSS', 'JavaScript', 'i18n'],
    github: 'PHOTOSITE-on-3lng-2.0',
    githubBase: GITHUB_BASE,
    live: `${GHPAGES}/PHOTOSITE-on-3lng-2.0/`,
    image: '/img/projects/photo-site-multilang.jpg',
    year: 2025,
    category: 'portfolio',
  },
  {
    id: 'diplom-consult',
    title: 'Diplom Consult',
    description: 'Full academic writing service website — thesis, coursework, dissertations. 6 services with pricing, contact form, light/dark theme.',
    descriptionRu: 'Сайт услуг академических работ: дипломные, курсовые, диссертации. 6 услуг с ценами, форма обратной связи, тёмная/светлая тема.',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'CSS Modules'],
    githubBase: GITHUB_BASE,
    live: 'https://diplom-consult.vercel.app',
    image: '/img/projects/diplom-consult.jpg',
    year: 2026,
    category: 'commercial',
  },
]
